### ISSUE TITLE
关注up报错

### ISSUE THREAD

**Issue by Hanx152** [TDK1969/nonebot_plugin_bilibilibot#13]
05-28 15:54:01 [ERROR] nonebot | Running matcher <Matcher from nonebot_plugin_bilibilibot, type=message, priority=1, temp=False> failed.
Traceback (most recent call last):
  File "D:\python\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\python\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "D:\python\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "D:\python\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "D:\python\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\python\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\python\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\python\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "D:\python\lib\site-packages\nb_cli\handlers\deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "D:\python\lib\site-packages\nonebot\__init__.py", line 259, in run
    get_driver().run(*args, **kwargs)
  File "D:\python\lib\site-packages\nonebot\drivers\fastapi.py", line 170, in run
    uvicorn.run(
  File "D:\python\lib\site-packages\uvicorn\main.py", line 463, in run
    server.run()
  File "D:\python\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "D:\python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\python\lib\asyncio\base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "D:\python\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "D:\python\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "D:\python\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "D:\python\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "D:\python\lib\site-packages\nonebot\message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "D:\python\lib\site-packages\nonebot\message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\python\lib\site-packages\nonebot\internal\matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\python\lib\site-packages\nonebot\internal\matcher.py", line 635, in simple_run
    await handler(
  File "D:\python\lib\site-packages\nonebot\dependencies\__init__.py", line 89, in __call__
    values = await self.solve(**kwargs)
  File "D:\python\lib\site-packages\nonebot\dependencies\__init__.py", line 188, in solve
    await checker._solve(**params)
  File "D:\python\lib\site-packages\nonebot\internal\params.py", line 208, in _solve
    if isinstance(event, field.type_):
  File "D:\python\lib\typing.py", line 769, in __instancecheck__
    return self.__subclasscheck__(type(obj))
  File "D:\python\lib\typing.py", line 777, in __subclasscheck__
    raise TypeError("Subscripted generics cannot be used with"
TypeError: Subscripted generics cannot be used with class and instance checks

**Comment by TDK1969** [comment]
感谢你的反馈，请补充如下信息：

1. 你使用nonebot的环境、bilibilibot的版本等；
2. 出现问题的完整日志内容，麻烦已文字形式放在代码块中方便查看；
3. 该问题是否能稳定复现；

**Comment by TDK1969** [comment]
目前看下来，似乎没有执行到bilibilibot插件的代码就出问题了

**Comment by Hanx152** [comment]
那能看出来是什么问题吗，我还装了那个analysis bilibili的插件
环境win10，插件版本2.0.4.1
重新安装了一次插件还是这样报错

**Comment by TDK1969** [comment]
nonebot的版本呢
我还真看不出来是哪里的问题，或者你可以只启用bilibilibot看是否能够正常使用

**Comment by Hanx152** [comment]
![GDSEG%3P UZ~C`S)ZEFZJKB](https://user-images.githubusercontent.com/103246532/170817694-7768aa4d-ad23-4b61-b5d7-79ed201262a6.png)
版本是这个吧
我用那个plugin manager的插件把除了bilibot之外的都禁用了，还是报错了

**Comment by TDK1969** [comment]
我的cli 的版本是0.6.6
nonebot2的版本呢？（通过`pip list | grep nonebot2`查看）

**Comment by Hanx152** [comment]
![VVODVTRIT{_H6CFY4ZLX$26](https://user-images.githubusercontent.com/103246532/170818248-c7e901cc-6401-4e80-9d59-aeeed7d2f29b.png)
这个好像用不了啊

**Comment by TDK1969** [comment]
windows版本可使用`pip show nonebot2`

**Comment by Hanx152** [comment]
2.0.0b3

**Comment by TDK1969** [comment]
我还没更新2.0.0b3，所以可能会存在一些问题，过几天我研究一下

**Comment by Hanx152** [comment]
好的，感谢
