### ISSUE TITLE
取关报错：另一个程序正在使用此文件，进程无法访问

### ISSUE THREAD

**Issue by Chinzicam** [TDK1969/nonebot_plugin_bilibilibot#18]
08-17 15:08:25 [ERROR] nonebot | Running matcher <Matcher from nonebot_plugin_bilibilibot, type=message, priority=1, temp=False> failed.
Traceback (most recent call last):
  File "c:\users\czc\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\czc\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\czc\AppData\Local\Programs\Python\Python38\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nb_cli\handlers\deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nonebot\__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nonebot\drivers\fastapi.py", line 170, in run
    uvicorn.run(
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\uvicorn\main.py", line 463, in run
    server.run()
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "c:\users\czc\appdata\local\programs\python\python38\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "c:\users\czc\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\czc\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\users\czc\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\users\czc\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nonebot\message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nonebot\message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nonebot\internal\matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nonebot\internal\matcher.py", line 635, in simple_run
    await handler(
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nonebot\dependencies\__init__.py", line 92, in __call__
    return await self.call(**values)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nonebot_plugin_bilibilibot\__init__.py", line 132, in unfollowUpCommandHandler
    successList, failList = await UnfollowUp(event, event.group_id, uidList, 1)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nonebot_plugin_bilibilibot\biliVideo.py", line 290, in UnfollowUp
    isSuccess, s = await UnfollowModifyUpFile(uid, userID, type)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nonebot_plugin_bilibilibot\biliVideo.py", line 215, in UnfollowModifyUpFile
    os.remove(upFile)
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'c:\\users\\czc\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\nonebot_plugin_bilibilibot/file/up/20165629.json'

所有**取关**部分都报错，其余正常

**Comment by Chinzicam** [comment]
上面是取关up的报错，这是取关主播的报错，可以稳定复现。
![DH1S {C0`E9 Y(CA2899NQB](https://user-images.githubusercontent.com/108013361/185059601-ed0937bd-c2db-475c-8486-c8a92bf83b29.png)


08-17 15:22:41 [ERROR] nonebot | Running matcher <Matcher from nonebot_plugin_bilibilibot, type=message, priority=1, temp=False> failed.
Traceback (most recent call last):
  File "c:\users\czc\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\czc\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\czc\AppData\Local\Programs\Python\Python38\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nb_cli\handlers\deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nonebot\__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nonebot\drivers\fastapi.py", line 170, in run
    uvicorn.run(
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\uvicorn\main.py", line 463, in run
    server.run()
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "c:\users\czc\appdata\local\programs\python\python38\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "c:\users\czc\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\czc\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\users\czc\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\users\czc\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nonebot\message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nonebot\message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nonebot\internal\matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nonebot\internal\matcher.py", line 635, in simple_run
    await handler(
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nonebot\dependencies\__init__.py", line 92, in __call__
    return await self.call(**values)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nonebot_plugin_bilibilibot\__init__.py", line 50, in unfollowStreamerCommandHandler
    successList, failList = await UnfollowStreamers(event, event.group_id, uidList, 1)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nonebot_plugin_bilibilibot\biliStream.py", line 321, in UnfollowStreamers
    isSuccess, s = await UnfollowModifyStreamerFile(uid, userID, type)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nonebot_plugin_bilibilibot\biliStream.py", line 246, in UnfollowModifyStreamerFile
    os.remove(streamerFile)
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'c:\\users\\czc\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\nonebot_plugin_bilibilibot/file/stream/70070.json'

**Comment by TDK1969** [comment]
问题已收到，目前正在努力开发数据库版本中==敬请期待
