### ISSUE TITLE
无法导入nonebot_plugin_bilibilibot

### ISSUE THREAD

**Issue by b1xcy** [TDK1969/nonebot_plugin_bilibilibot#21]
windows10环境，其他插件正常导入
错误日志如下：
09-10 02:32:52 [SUCCESS] nonebot | NoneBot is initializing...
09-10 02:32:52 [INFO] nonebot | Current Env: dev
09-10 02:32:52 [DEBUG] nonebot | Loaded Config: {'driver': '~fastapi', 'host': IPv4Address('127.0.0.1'), 'port': 12340, 'log_level': 'DEBUG', 'api_timeout': 30.0, 'superusers': {'1446833475'}, 'nickname': {'QQBot'}, 'command_start': {'!'}, 'command_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'environment': 'dev', 'supersusers': ['1446833475'], 'fastapi_reload': True}
09-10 02:32:53 [DEBUG] nonebot | Succeeded to load adapter "OneBot V11"
09-10 02:32:53 [SUCCESS] nonebot | Succeeded to import "echo"
09-10 02:32:54 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_gocqhttp"
09-10 02:32:54 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_analysis_bilibili"
09-10 02:32:54 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_apscheduler"
09-10 02:32:55 [DEBUG] nonebot_plugin_bilibilibot | 初始化数据库
09-10 02:32:55 [DEBUG] nonebot_plugin_bilibilibot | 数据库初始化完毕
09-10 02:32:55 [ERROR] nonebot | Failed to import "nonebot_plugin_bilibilibot"
Traceback (most recent call last):
  File "E:/demo/bot/QQBot\bot.py", line 27, in <module>
    nonebot.load_plugin("nonebot_plugin_bilibilibot")
  File "C:\Users\14468\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin\load.py", line 28, in load_plugin
    return manager.load_plugin(module_path)
> File "C:\Users\14468\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin\manager.py", line 144, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\14468\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\14468\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin\manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\14468\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot_plugin_bilibilibot\__init__.py", line 12, in <module>
    from .biliStream import *
  File "C:\Users\14468\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot_plugin_bilibilibot\biliStream.py", line 9, in <module>
    from .basicFunc import *
  File "C:\Users\14468\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot_plugin_bilibilibot\basicFunc.py", line 12, in <module>
    from .db import bili_database
  File "C:\Users\14468\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot_plugin_bilibilibot\db.py", line 551, in <module>
    bili_database.get_from_json()
  File "C:\Users\14468\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot_plugin_bilibilibot\db.py", line 468, in get_from_json
    for json_file_name in os.listdir(dir_path + "user"):
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'C:\\Users\\14468\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\nonebot_plugin_bilibilibot/file/user'
09-10 02:32:55 [WARNING] __main__ | Always use `nb run` to start the bot instead of manually running!
09-10 02:32:55 [SUCCESS] nonebot | Running NoneBot...
09-10 02:32:55 [DEBUG] nonebot | Loaded adapters: OneBot V11
09-10 02:32:55 [INFO] uvicorn | Will watch for changes in these directories: ['E:\\demo\\bot\\QQBot']
09-10 02:32:55 [INFO] uvicorn | Uvicorn running on http://127.0.0.1:12340 (Press CTRL+C to quit)
09-10 02:32:55 [INFO] uvicorn | Started reloader process [16544] using WatchFiles
09-10 02:32:55 [SUCCESS] nonebot | NoneBot is initializing...
09-10 02:32:55 [INFO] nonebot | Current Env: dev
09-10 02:32:55 [DEBUG] nonebot | Loaded Config: {'driver': '~fastapi', 'host': IPv4Address('127.0.0.1'), 'port': 12340, 'log_level': 'DEBUG', 'api_timeout': 30.0, 'superusers': {'1446833475'}, 'nickname': {'QQBot'}, 'command_start': {'!'}, 'command_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'environment': 'dev', 'fastapi_reload': True, 'supersusers': ['1446833475']}
09-10 02:32:55 [DEBUG] nonebot | Succeeded to load adapter "OneBot V11"
09-10 02:32:55 [SUCCESS] nonebot | Succeeded to import "echo"
09-10 02:32:57 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_gocqhttp"
09-10 02:32:57 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_analysis_bilibili"
09-10 02:32:57 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_apscheduler"
09-10 02:32:57 [DEBUG] nonebot_plugin_bilibilibot | 初始化数据库
09-10 02:32:57 [DEBUG] nonebot_plugin_bilibilibot | 数据库初始化完毕
09-10 02:32:57 [ERROR] nonebot | Failed to import "nonebot_plugin_bilibilibot"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\14468\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\14468\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\14468\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\14468\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\14468\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\14468\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\14468\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\demo\bot\QQBot\bot.py", line 27, in <module>
    nonebot.load_plugin("nonebot_plugin_bilibilibot")
  File "C:\Users\14468\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin\load.py", line 28, in load_plugin
    return manager.load_plugin(module_path)
> File "C:\Users\14468\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin\manager.py", line 144, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\14468\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\14468\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin\manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\14468\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot_plugin_bilibilibot\__init__.py", line 12, in <module>
    from .biliStream import *
  File "C:\Users\14468\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot_plugin_bilibilibot\biliStream.py", line 9, in <module>
    from .basicFunc import *
  File "C:\Users\14468\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot_plugin_bilibilibot\basicFunc.py", line 12, in <module>
    from .db import bili_database
  File "C:\Users\14468\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot_plugin_bilibilibot\db.py", line 551, in <module>
    bili_database.get_from_json()
  File "C:\Users\14468\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot_plugin_bilibilibot\db.py", line 468, in get_from_json
    for json_file_name in os.listdir(dir_path + "user"):
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'C:\\Users\\14468\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\nonebot_plugin_bilibilibot/file/user'

**Comment by TDK1969** [comment]
感谢反馈！这是旧代码的遗留问题，将尽快修复。

**Comment by TDK1969** [comment]
若在修复前想正常使用，请将`db.py`文件中的最后一行`bili_database.get_from_json()`注释掉，即可正常运行。

**Comment by bix-cy** [comment]
依然不行，报错日志如下：
09-11 16:47:56 [SUCCESS] nonebot | NoneBot is initializing...
09-11 16:47:56 [INFO] nonebot | Current Env: dev
09-11 16:47:56 [DEBUG] nonebot | Loaded Config: {'driver': '~fastapi', 'host': IPv4Address('127.0.0.1'), 'port': 12340, 'log_level': 'DEBUG', 'api_timeout': 30.0, 'superusers': {'1446833475'}, 'nickname': {'QQBot'}, 'command_start': {'!'}, 'command_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'proxies_socks5': '<127.0.0.1:7890>', 'supersusers': ['1446833475'], 'setu2_cd': '<2>', 'fastapi_reload': True, 'environment': 'dev'}
09-11 16:47:56 [DEBUG] nonebot | Succeeded to load adapter "OneBot V11"
09-11 16:47:57 [SUCCESS] nonebot | Succeeded to import "echo"
09-11 16:47:58 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_gocqhttp"
09-11 16:48:00 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_apscheduler"
09-11 16:48:00 [DEBUG] nonebot_plugin_bilibilibot | 初始化数据库
09-11 16:48:00 [DEBUG] nonebot_plugin_bilibilibot | 数据库初始化完毕
09-11 16:48:00 [ERROR] nonebot | Failed to import "nonebot_plugin_bilibilibot"
Traceback (most recent call last):
  File "C:\Users\14468\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\14468\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\14468\AppData\Local\Programs\Python\Python310\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\14468\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\14468\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\14468\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\14468\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\14468\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\14468\AppData\Local\Programs\Python\Python310\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "C:\Users\14468\AppData\Local\Programs\Python\Python310\lib\site-packages\nb_cli\handlers\deploy.py", line 20, in run_bot
    module = importlib.import_module(module_name)
  File "C:\Users\14468\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\demo\bot\QQBot\.\bot.py", line 27, in <module>
    nonebot.load_plugin("nonebot_plugin_bilibilibot")
  File "C:\Users\14468\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\load.py", line 28, in load_plugin
    return manager.load_plugin(module_path)
> File "C:\Users\14468\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\manager.py", line 144, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\14468\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\14468\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\14468\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_bilibilibot\__init__.py", line 12, in <module>
    from .biliStream import *
  File "C:\Users\14468\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_bilibilibot\biliStream.py", line 9, in <module>
    from .basicFunc import *
  File "C:\Users\14468\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_bilibilibot\basicFunc.py", line 12, in <module>
    from .db import bili_database
  File "C:\Users\14468\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_bilibilibot\db.py", line 551, in <module>
    bili_database.get_from_json()
  File "C:\Users\14468\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_bilibilibot\db.py", line 496, in get_from_json
    for json_file_name in os.listdir(dir_path + "group"):
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'C:\\Users\\14468\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\nonebot_plugin_bilibilibot/file/group'
09-11 16:48:00 [SUCCESS] nonebot | Running NoneBot...
09-11 16:48:00 [DEBUG] nonebot | Loaded adapters: OneBot V11
09-11 16:48:00 [INFO] uvicorn | Will watch for changes in these directories: ['E:\\demo\\bot\\QQBot']
09-11 16:48:00 [INFO] uvicorn | Uvicorn running on http://127.0.0.1:12340 (Press CTRL+C to quit)
09-11 16:48:00 [INFO] uvicorn | Started reloader process [25436] using WatchFiles
09-11 16:48:00 [SUCCESS] nonebot | NoneBot is initializing...
09-11 16:48:00 [INFO] nonebot | Current Env: dev
09-11 16:48:00 [DEBUG] nonebot | Loaded Config: {'driver': '~fastapi', 'host': IPv4Address('127.0.0.1'), 'port': 12340, 'log_level': 'DEBUG', 'api_timeout': 30.0, 'superusers': {'1446833475'}, 'nickname': {'QQBot'}, 'command_start': {'!'}, 'command_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'supersusers': ['1446833475'], 'fastapi_reload': True, 'setu2_cd': '<2>', 'environment': 'dev', 'proxies_socks5': '<127.0.0.1:7890>'}
09-11 16:48:00 [DEBUG] nonebot | Succeeded to load adapter "OneBot V11"
09-11 16:48:00 [SUCCESS] nonebot | Succeeded to import "echo"
09-11 16:48:02 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_gocqhttp"
09-11 16:48:02 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_apscheduler"
09-11 16:48:02 [DEBUG] nonebot_plugin_bilibilibot | 初始化数据库
09-11 16:48:02 [DEBUG] nonebot_plugin_bilibilibot | 数据库初始化完毕
09-11 16:48:02 [ERROR] nonebot | Failed to import "nonebot_plugin_bilibilibot"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\14468\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\14468\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "C:\Users\14468\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\14468\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\14468\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\14468\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\14468\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\14468\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\14468\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\14468\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\14468\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\14468\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\server.py", line 67, in serve
    config.load()
  File "C:\Users\14468\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\config.py", line 479, in load
    self.loaded_app = import_from_string(self.app)
  File "C:\Users\14468\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\Users\14468\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\demo\bot\QQBot\.\bot.py", line 27, in <module>
    nonebot.load_plugin("nonebot_plugin_bilibilibot")
  File "C:\Users\14468\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\load.py", line 28, in load_plugin
    return manager.load_plugin(module_path)
> File "C:\Users\14468\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\manager.py", line 144, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\14468\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\14468\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\14468\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_bilibilibot\__init__.py", line 12, in <module>
    from .biliStream import *
  File "C:\Users\14468\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_bilibilibot\biliStream.py", line 9, in <module>
    from .basicFunc import *
  File "C:\Users\14468\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_bilibilibot\basicFunc.py", line 12, in <module>
    from .db import bili_database
  File "C:\Users\14468\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_bilibilibot\db.py", line 551, in <module>
    bili_database.get_from_json()
  File "C:\Users\14468\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_bilibilibot\db.py", line 496, in get_from_json
    for json_file_name in os.listdir(dir_path + "group"):
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'C:\\Users\\14468\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\nonebot_plugin_bilibilibot/file/group'
09-11 16:48:02 [INFO] uvicorn | Started server process [25852]
09-11 16:48:02 [INFO] uvicorn | Waiting for application startup.

**Comment by b1xcy** [comment]
在重新安装nonebot_plugin_gocqhttp,nonebot_plugin_apscheduler,nonebot_plugin_bilibilibot后修改db.py文件正常运行。
