### ISSUE TITLE
No module named 'nonebot_plugin_bilibilibot.bili_src'

### ISSUE THREAD

**Issue by DGHOSTI** [TDK1969/nonebot_plugin_bilibilibot#32]
12-18 01:42:58 [ERROR] nonebot | Failed to import "nonebot_plugin_bilibilibot"
Traceback (most recent call last):
  File "/usr/local/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
  File "/usr/local/lib/python3.10/dist-packages/nb_cli/handlers/deploy.py", line 20, in run_bot
    module = importlib.import_module(module_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/qqbot/nonebot/./bot.py", line 27, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "/usr/local/lib/python3.10/dist-packages/nonebot/plugin/load.py", line 122, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/plugin/load.py", line 59, in load_all_plugins
    return manager.load_all_plugins()
  File "/usr/local/lib/python3.10/dist-packages/nonebot/plugin/manager.py", line 168, in load_all_plugins
    return set(
  File "/usr/local/lib/python3.10/dist-packages/nonebot/plugin/manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/usr/local/lib/python3.10/dist-packages/nonebot/plugin/manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/usr/local/lib/python3.10/dist-packages/nonebot/plugin/manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_bilibilibot/__init__.py", line 13, in <module>
    from .bili_src.biliStream import *
ModuleNotFoundError: No module named 'nonebot_plugin_bilibilibot.bili_src'

**Comment by TDK1969** [comment]
请提供[nonebot_plugin_bilibilibot](https://github.com/TDK1969/nonebot_plugin_bilibilibot)的版本

**Comment by DGHOSTI** [comment]
最新版2.3.0

**Comment by eigeen** [comment]
最新版同样出现此bug，只在使用nb plugin install的方式下出现。使用本地安装方法不会出现此问题。

**Comment by TDK1969** [comment]
> 最新版同样出现此bug，只在使用nb plugin install的方式下出现。使用本地安装方法不会出现此问题。

收到，正在排查问题中，感觉是包的import出了问题

**Comment by eigeen** [comment]
> > 最新版同样出现此bug，只在使用nb plugin install的方式下出现。使用本地安装方法不会出现此问题。
> 
> 收到，正在排查问题中，感觉是包的import出了问题

另发现一个问题，使用/help会读取plugins\nonebot_plugin_bilibilibot\bili_src\file\source\help.json内容（file\source在bili_src内部），而在您的仓库中，这个file\source目录和bili_src在同级目录下，是否提交时目录组织出现了问题？

**Comment by TDK1969** [comment]
问题已排查完毕，使用了错误的方式进行打包，现在可以正常使用nb plugin install nonebot-plugin-bilibilibot进行插件安装

**Comment by DGHOSTI** [comment]
添加个lxml模块已经正常安装了，感谢作者大佬
