### ISSUE TITLE
关于file\source和bili_src目录结构的问题

### ISSUE THREAD

**Issue by eigeen** [TDK1969/nonebot_plugin_bilibilibot#33]
发现一个问题，使用/help会读取plugins\nonebot_plugin_bilibilibot\bili_src\file\source\help.json内容（file\source在bili_src内部），而在您的仓库中，这个file\source目录和bili_src在同级目录下，是否提交时目录组织出现了问题？

引用自https://github.com/TDK1969/nonebot_plugin_bilibilibot/issues/32 ，单独开了一个issue

**Comment by DGHOSTI** [comment]
12-26 11:14:31 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_bilibilibot) failed.
Traceback (most recent call last):
  File "/Virtual/Botenv/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/Virtual/Botenv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Virtual/Botenv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Virtual/Botenv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Virtual/Botenv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Virtual/Botenv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Virtual/Botenv/lib/python3.10/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
  File "/Virtual/Botenv/lib/python3.10/site-packages/nb_cli/handlers/deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "/Virtual/Botenv/lib/python3.10/site-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "/Virtual/Botenv/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 172, in run
    uvicorn.run(
  File "/Virtual/Botenv/lib/python3.10/site-packages/uvicorn/main.py", line 569, in run
    server.run()
  File "/Virtual/Botenv/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Virtual/Botenv/lib/python3.10/site-packages/nonebot/message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/Virtual/Botenv/lib/python3.10/site-packages/nonebot/message.py", line 188, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/Virtual/Botenv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 727, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/Virtual/Botenv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 702, in simple_run
    await handler(
  File "/Virtual/Botenv/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/Virtual/Botenv/lib/python3.10/site-packages/nonebot_plugin_bilibilibot/__init__.py", line 349, in sendHelpMsg
    with open(f'{PackagePath}/file/source/help.json', 'r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Virtual/Botenv/lib/python3.10/site-packages/nonebot_plugin_bilibilibot/bili_src/file/source/help.json'

出现了同样的问题

**Comment by TDK1969** [comment]
准备提交修复版本

**Comment by TDK1969** [comment]
新版本2.3.1已解决该问题
