### ISSUE TITLE
插件导入报错

### ISSUE THREAD

**Issue by Cloudwhile** [TDK1969/nonebot_plugin_bilibilibot#36]
12-23 16:32:15 [ERROR] nonebot | Failed to import "nonebot_plugin_bilibilibot"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\Desktop\bot\mcqq\mcqq_bot\bot.py", line 23, in <module>
    nonebot.load_plugin("nonebot_plugin_bilibilibot")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_bilibilibot\__init__.py", line 13, in <module>
    from .bili_src.biliStream import *
ModuleNotFoundError: No module named 'nonebot_plugin_bilibilibot.bili_src'

**Comment by TDK1969** [comment]
已收到问题反馈，正在解决中
暂时的解决办法是clone到nonebot的plugin目录下

**Comment by TDK1969** [comment]
问题已排查完毕，使用了错误的方式进行打包，现在可以正常使用`nb plugin install nonebot-plugin-bilibilibot`进行插件安装

**Comment by Cloudwhile** [comment]
12-26 11:17:10 [ERROR] nonebot | Failed to import "nonebot_plugin_bilibilibot"
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\bot\mcqq\mcqq_bot\bot.py", line 23, in <module>
    nonebot.load_plugin("nonebot_plugin_bilibilibot")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_bilibilibot\__init__.py", line 13, in <module>
    from .bili_src.biliStream import *
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_bilibilibot\bili_src\biliStream.py", line 10, in <module>
    from .bili_client import bili_client
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_bilibilibot\bili_src\bili_client.py", line 3, in <module>
    from lxml import etree
ModuleNotFoundError: No module named 'lxml'
这个是？
