### ISSUE TITLE
出现预期之外的错误，可能是网络问题 bilibot如何设置代理

### ISSUE THREAD

**Issue by UHD630** [TDK1969/nonebot_plugin_bilibilibot#41]
关注动态主 <*******>时发生意料之外的错误
错误类型: <class 'json.decoder.JSONDecodeError'>
错误值: Extra data: line 1 column 47 (char 46)
Traceback (most recent call last):
  File "C:\Users\18252\Desktop\QQrob\qqbot\.venv\Lib\site-packages\nonebot_plugin_bilibilibot\bili_src\bili_dynamic.py", line 152, in follow_dynamic
    u_name, pin_id_str, latest_timestamp = await bili_client.init_dynamic_info(uid)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\18252\Desktop\QQrob\qqbot\.venv\Lib\site-packages\nonebot_plugin_bilibilibot\bili_src\bili_client.py", line 518, in init_dynamic_info
    response1 = response1.json()
                ^^^^^^^^^^^^^^^^
  File "C:\Users\18252\Desktop\QQrob\qqbot\.venv\Lib\site-packages\httpx\_models.py", line 756, in json
    return jsonlib.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 47 (char 46)

**Comment by TDK1969** [comment]
已在2.3.2更新中解决。
