### ISSUE TITLE
插件加载出错

### ISSUE THREAD

**Issue by ElainaFanBoy** [TDK1969/nonebot_plugin_bilibilibot#43]
[ERROR] nonebot | Failed to import "nonebot_plugin_bilibilibot"
Traceback (most recent call last):
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\bot.py", line 26, in <module>
    nonebot.load_plugins("src/plugins")
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\plugin\load.py", line 48, in load_plugins
    return manager.load_all_plugins()
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\plugin\manager.py", line 175, in load_all_plugins
    return set(
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\plugin\manager.py", line 176, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\plugin\manager.py", line 145, in load_plugin
    module = importlib.import_module(
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\plugin\manager.py", line 240, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\src\plugins\nonebot_plugin_bilibilibot\__init__.py", line 13, in <module>
    from .bili_src.biliStream import *
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\src\plugins\nonebot_plugin_bilibilibot\bili_src\biliStream.py", line 10, in <module>
    from .bili_client import bili_client
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\src\plugins\nonebot_plugin_bilibilibot\bili_src\bili_client.py", line 749, in <module>
    bili_client = BiliClient()
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\src\plugins\nonebot_plugin_bilibilibot\bili_src\bili_client.py", line 83, in __init__
    self.__proxy_lock__ = asyncio.Lock()
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\locks.py", line 81, in __init__
    self._loop = events.get_event_loop()
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\events.py", line 642, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'MainThread'.

**Comment by TDK1969** [comment]
请将`bili_src/bili_client.py`中第83行的
```
self.proxy_lock = asyncio.Lock()
```
注释掉即可

**Comment by ElainaFanBoy** [comment]
> 请将`bili_src/bili_client.py`中第83行的
> 
> ```
> self.proxy_lock = asyncio.Lock()
> ```
> 
> 注释掉即可

可以了，辛苦
