### ISSUE TITLE
【错误回报】获取直播间信息错误

### ISSUE THREAD

**Issue by NAOLIU** [TDK1969/nonebot_plugin_bilibilibot#5]
系统为Win10，go-qchttp版本和nonebot版本均无问题
一直无法获取直播间信息，报错信息刷屏

04-21 03:08:46 [ERROR] nonebot_plugin_bilibilibot | B站整合~直播
【错误报告】
检测用户XXXXB站直播时发生错误
错误类型: <class 'AssertionError'>
错误值: 获取直播间信息时连接错误, status_code = 412
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_bilibilibot\biliStream.py", line 73, in CheckBiliStream
    isStreaming, title, coverURL = GetBiliStream(filename.split('.')[0])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_bilibilibot\biliStream.py", line 37, in GetBiliStream
    assert response.status_code == 200, '获取直播间信息时连接错误, status_code = {}'.format(response.status_code)
AssertionError: 获取直播间信息时连接错误, status_code = 412

**Comment by TDK1969** [comment]
1. 请问是只有获取直播间信息时发生错误吗，视频、番剧功能是否正常？
2. 请将`biliStream.py`文件中，函数`GetBiliStream`中的`assert response.status_code == 200, '获取直播间信息时连接错误, status_code = {}'.format(response.status_code)` 修改为 `assert response.status_code == 200, f'获取直播间信息时连接错误, status_code = {response.status_code}, error_msg = {response.content}'`，并再次运行，查看具体报错内容
